---
title: "betting enums"
---

### MarketProjection

* COMPETITION
    - If not selected then the competition will not be returned with marketCatalogue.
* EVENT
    - If not selected then the event will not be returned with marketCatalogue.
* EVENT_TYPE
    - If not selected then the eventType will not be returned with marketCatalogue.
* MARKET_START_TIME
    - If not selected then the start time will not be returned with marketCatalogue.
* MARKET_DESCRIPTION
    - If not selected then the description will not be returned with marketCatalogue.
* RUNNER_DESCRIPTION
    - If not selected then the runners will not be returned with marketCatalogue.
* RUNNER_METADATA
    - If not selected then the runner metadata will not be returned with marketCatalogue. If selected then RUNNER_DESCRIPTION will also be returned regardless of whether it is included as a market projection.

### PriceData

* SP_AVAILABLE
    - Amount available for the BSP auction.
* SP_TRADED
    - Amount traded in the BSP auction.
* EX_BEST_OFFERS
    - Only the best prices available for each runner, to requested price depth.
* EX_ALL_OFFERS
    - EX_ALL_OFFERS trumps EX_BEST_OFFERS if both settings are present.
* EX_TRADED
    - Amount traded on the exchange.

### MatchProjection

* NO_ROLLUP
    - No rollup, return raw fragments.
* ROLLED_UP_BY_PRICE
    - Rollup matched amounts by distinct matched prices per side.
* ROLLED_UP_BY_AVG_PRICE
    - Rollup matched amounts by average matched price per side.

### OrderProjection

* ALL
    - EXECUTABLE and EXECUTION_COMPLETE orders.
* EXECUTABLE
    - An order that has a remaining unmatched portion.
* EXECUTION_COMPLETE
    - An order that does not have any remaining unmatched portion.

### MarketStatus

* INACTIVE
    - The market has been created but isn't yet available.
* OPEN
    - The market is open for betting.
* SUSPENDED
    - The market is suspended and not available for betting.
* CLOSED
    - The market has been settled and is no longer available for betting.

### RunnerStatus

* ACTIVE
    - ACTIVE
* WINNER
    - WINNER
* LOSER
    - LOSER
* REMOVED_VACANT
    - REMOVED_VACANT applies to Greyhounds. Greyhound markets always return a fixed number of runners (traps). If a dog has been removed, the trap is shown as vacant.
* REMOVED
    - REMOVED
* HIDDEN
    - The selection is hidden from the market.  This occurs in Horse Racing markets were runners is hidden when it is doesn’t hold an official entry following an entry stage. This could be because the horse was never entered or because they have been scratched from a race at a declaration stage. All matched customer bet prices are set to 1.0 even if there are later supplementary stages. Should it appear likely that a specific runner may actually be supplemented into the race this runner will be reinstated with all matched customer bets set back to the original prices.

### TimeGranularity

* DAYS
* HOURS
* MINUTES

### Side

* BACK
    - To back a team, horse or outcome is to bet on the selection to win.
* LAY
    - To lay a team, horse, or outcome is to bet on the selection to lose.

### OrderStatus

* EXECUTION_COMPLETE
    - An order that does not have any remaining unmatched portion.
* EXECUTABLE
    - An order that has a remaining unmatched portion.

### OrderBy

* BY_BET
    - **Deprecated**. Use BY_PLACE_TIME instead. Order by placed time, then bet id.
* BY_MARKET
    - Order by market id, then placed time, then bet id.
* BY_MATCH_TIME
    - Order by time of last matched fragment (if any), then placed time, then bet id. Filters out orders which have no matched date. The dateRange filter (if specified) is applied to the matched date.
* BY_PLACE_TIME
    - Order by placed time, then bet id. This is an alias of to be deprecated BY_BET. The dateRange filter (if specified) is applied to the placed date.
* BY_SETTLED_TIME
    - Order by time of last settled fragment (if any due to partial market settlement), then by last match time, then placed time, then bet id. Filters out orders which have not been settled.  The dateRange filter (if specified) is applied to the settled date.
* BY_VOID_TIME
    - Order by time of last voided fragment (if any), then by last match time, then placed time, then bet id. Filters out orders which have not been voided. The dateRange filter (if specified) is applied to the voided date.

### SortDir

* EARLIEST_TO_LATEST
    - Order from earliest value to latest e.g. lowest betId is first in the results.
* LATEST_TO_EARLIEST
    - Order from the latest value to the earliest e.g. highest betId is first in the results.

### OrderType

* LIMIT
    - A normal exchange limit order for immediate execution.
* LIMIT_ON_CLOSE
    - Limit order for the auction (SP).
* MARKET_ON_CLOSE
    - Market order for the auction (SP).

### MarketSort

* MINIMUM_TRADED
    - Minimum traded volume
* MAXIMUM_TRADED
    - Maximum traded volume
* MINIMUM_AVAILABLE
    - Minimum available to match
* MAXIMUM_AVAILABLE
    - Maximum available to match
* FIRST_TO_START
    - The closest markets based on their expected start time.
* LAST_TO_START
    - The most distant markets based on their expected start time.

### MarketBettingType

* ODDS
    - Odds Market
* LINE
    - Line Market
* RANGE
    - Range Market
* ASIAN_HANDICAP_DOUBLE_LINE
    - Asian Handicap Market
* ASIAN_HANDICAP_SINGLE_LINE
    - Asian Single Line Market
* FIXED_ODDS
    - Sportsbook Odds Market. This type is deprecated and will be removed in future releases, when Sportsbook markets will be represented as ODDS market but with a different product type.

### ExecutionReportStatus

* SUCCESS
    - Order processed successfully
* FAILURE
    - Order failed.
* PROCESSED_WITH_ERRORS
    - The order itself has been accepted, but at least one (possibly all) actions have generated errors. This error only occurs for replaceOrders, cancelOrders and updateOrders operations.  The placeOrders operation will not return PROCESSED_WITH_ERRORS status as it is an atomic operation.
* TIMEOUT
    - Order timed out.

### ExecutionReportErrorCode

* ERROR_IN_MATCHER
    - The matcher is not healthy
* PROCESSED_WITH_ERRORS
    - The order itself has been accepted, but at least one (possibly all) actions have generated errors
* BET_ACTION_ERROR
    - There is an error with an action that has caused the entire order to be rejected. Check the instructionReports errorCode for the reason for the rejection of the order.
* INVALID_ACCOUNT_STATE
    - Order rejected due to the account's status (suspended, inactive, dup cards)
* INVALID_WALLET_STATUS
    - Order rejected due to the account's wallet's status
* INSUFFICIENT_FUNDS
    - Account has exceeded its exposure limit or available to bet limit
* LOSS_LIMIT_EXCEEDED
    - The account has exceed the self imposed loss limit
* MARKET_SUSPENDED
    - Market is suspended
* MARKET_NOT_OPEN_FOR_BETTING
    - Market is not open for betting. It is either not yet active, suspended or closed awaiting settlement.
* DUPLICATE_TRANSACTION
    - Duplicate customer reference data submitted - Please note: There is a time window associated with the de-duplication of duplicate submissions which is 60 second
* INVALID_ORDER
    - Order cannot be accepted by the matcher due to the combination of actions. For example, bets being edited are not on the same market, or order includes both edits and placement
* INVALID_MARKET_ID
    - Market doesn't exist
* PERMISSION_DENIED
    - Business rules do not allow order to be placed. You are either attempting to place the order using a Delayed Application Key or from a restricted jurisdiction (i.e. USA)
* DUPLICATE_BETIDS
    - duplicate bet ids found
* NO_ACTION_REQUIRED
    - Order hasn't been passed to matcher as system detected there will be no state change
* SERVICE_UNAVAILABLE
    - The requested service is unavailable
* REJECTED_BY_REGULATOR
    - The regulator rejected the order. On the Italian Exchange this error will occur if more than 50 bets are sent in a single placeOrders request.

### PersistenceType

* LAPSE
    - Lapse the order when the market is turned in-play
* PERSIST
    - Persist the order to in-play. The bet will be place automatically into the in-play market at the start of the event.
* MARKET_ON_CLOSE
    - Put the order into the auction (SP) at turn-in-play

### InstructionReportStatus

* SUCCESS
* FAILURE
* TIMEOUT

### InstructionReportErrorCode

* INVALID_BET_SIZE
    - bet size is invalid for your currency or your regulator
* INVALID_RUNNER
    - Runner does not exist, includes vacant traps in greyhound racing
* BET_TAKEN_OR_LAPSED
    - Bet cannot be cancelled or modified as it has already been taken or has lapsed Includes attempts to cancel/modify market on close BSP bets and cancelling limit on close BSP bets
* BET_IN_PROGRESS
    - No result was received from the matcher in a timeout configured for the system
* RUNNER_REMOVED
    - Runner has been removed from the event
* MARKET_NOT_OPEN_FOR_BETTING
    - Attempt to edit a bet on a market that has closed.
* LOSS_LIMIT_EXCEEDED
    - The action has caused the account to exceed the self imposed loss limit
* MARKET_NOT_OPEN_FOR_BSP_BETTING
    - Market now closed to bsp betting. Turned in-play or has been reconciled
* INVALID_PRICE_EDIT
    - Attempt to edit down the price of a bsp limit on close lay bet, or edit up the price of a limit on close back bet
* INVALID_ODDS
    - Odds not on price ladder - either edit or placement
* INSUFFICIENT_FUNDS
    - Insufficient funds available to cover the bet action. Either the exposure limit or available to bet limit would be exceeded
* INVALID_PERSISTENCE_TYPE
    - Invalid persistence type for this market, e.g. KEEP for a non bsp market
* ERROR_IN_MATCHER
    - A problem with the matcher prevented this action completing successfully
* INVALID_BACK_LAY_COMBINATION
    - The order contains a back and a lay for the same runner at overlapping prices. This would guarantee a self match. This also applies to BSP limit on close bets
* ERROR_IN_ORDER
    - The action failed because the parent order failed
* INVALID_BID_TYPE
    - Bid type is mandatory
* INVALID_BET_ID
    - Bet for id supplied has not been found
* CANCELLED_NOT_PLACED
    - Bet cancelled but replacement bet was not placed
* RELATED_ACTION_FAILED
    - Action failed due to the failure of a action on which this action is dependent
* NO_ACTION_REQUIRED
    - the action does not result in any state change. eg changing a persistence to it's current value

### RollupModel

* STAKE
    - The volumes will be rolled up to the minimum value which is >= rollupLimit.
* PAYOUT
    - The volumes will be rolled up to the minimum value where the payout( price * volume ) is >= rollupLimit.
* MANAGED_LIABILITY
    - The volumes will be rolled up to the minimum value which is >= rollupLimit, until a lay price threshold. There after, the volumes will be rolled up to the minimum value such that the liability >= a minimum liability. Not supported as yet.
* NONE
    - No rollup will be applied. However the volumes will be filtered by currency specific minimum stake unless overridden specifically for the channel.

### GroupBy

* EVENT_TYPE
    - A roll up of settled P&L, commission paid and number of bet orders, on a specified event type
* EVENT
    - A roll up of settled P&L, commission paid and number of bet orders, on a specified event
* MARKET
    - A roll up of settled P&L, commission paid and number of bet orders, on a specified market
* SIDE
    - An averaged roll up of settled P&L, and number of bets, on the specified side of a specified selection within a specified market, that are either settled or voided
* BET
    - The P&L, commission paid, side and regulatory information etc, about each individual bet order

### BetStatus

* SETTLED
    - A matched bet that was settled normally
* VOIDED
    - A matched bet that was subsequently voided by Betfair, before, during or after settlement
* LAPSED
    - Unmatched bet that was cancelled by Betfair (for example at turn in play).
* CANCELLED
    - Unmatched bet that was cancelled by an explicit customer action.

    <a href="https://github.com/durtal/betfaiR" class="github-corner"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#d9230f; color:#fcfcfc; position: absolute; top: 0; border: 0; right: 0;"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>
