---
title: "intro"
---

The `betfaiR` package will eventually provide R users full access to the Betfair API, retrieving data and placing bets.  

The **primary** function of the package is [`betfair`](betfair.html) which requires users to enter their login details, including an API key (see Betfair [documentation](https://api.developer.betfair.com/services/webapps/docs/display/1smk3cen4v3lu3yomq5qye0ni/Application+Keys) on how to get an API key).  The function returns an environment with various methods for querying and retrieving data from Betfair.

This is not to say that it is the only way to use this package, all the functions that `betfair` uses are available, but `betfair` aims to keep the workspace free of unnecessary variables as queries are developed and saved.

The `betfair` function logs in, and for each of the methods the following functions are called:

step | function | arguments | details | return
-----|----------|-----------|---------|-------
**1** | [`betfair_login`](betfair_login.html) | _usr_, _pwd_, _key_ | login function with betfair username, password, and key | list with a session token
**2** | [`base_request`](request_functions.html#base_request) | _filter_, _method_ | builds a basic request object | list with class that matches _method_ param
**3** | [`betfair_request`](request_functions.html#betfair_request) | _x_, _..._ | fleshes out the request object | json object ready to be included in a POST request
**4** | [`betfair_POST`](betfair_POST.html) | _body_ | betfair POST, includes the request object returned in step **3**, and the session token returned in **1** | response object
**5** | `httr::content` | _response_ | response object to be parsed into a list | list with data
**6** | [`betfair_check`](betfair_check.html) | _response_, _method_ | check the response is valid, log errors if not, apply class _method_ to list ahead of step **7** | list
**7** | [`betfair_parse`](betfair_parse.html) | _response_ | parses the response object | list of dataframes or dataframe

<a href="https://github.com/durtal/betfaiR" class="github-corner"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#d9230f; color:#fcfcfc; position: absolute; top: 0; border: 0; right: 0;"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>
