---
title: "placeOrders"
---

**This function allows bets to be placed, and could require some additional work so proceed with great caution**

Having logged in using the [`betfair`](betfair.html) function and found the market and selection that you wish to place a bet on using either [`marketCatalogue`](methods_marketCatalogue.html) or [`marketBook`](methods_marketBook.html) methods (or a combination of both).  A bet can be struck using `placeOrders`.

### usage

```{r eval=FALSE}
bf$placeOrders(marketId,
               selectionId,
               orderType = c("LIMIT", "LIMIT_ON_CLOSE", "MARKET_ON_CLOSE"),
               handicap = "0",
               side = "BACK",
               limitOrder = limitOrder(),
               limitOnCloseOrder = limitOnCloseOrder(),
               marketOnCloseOrder = NULL)
```

### arguments

param | details
------|--------
`marketId` | unique market id into which the bet will be placed
`selectionId` | the unique id for the selection in the market, this will be a horse, a team, etc, these ids can be found using the [`marketCatalogue`](methods_marketCatalogue.html) and [`marketBook`](methods_marketBook.html) methods
`orderType` | the type of order, **LIMIT** - a normal exchange order for immediate execution, **LIMIT\_ON\_CLOSE** - limit oder for the auction (SP bet with a price limit), **MARKET\_ON\_CLOSE** - market order for the auction, SP bet regardless of price.
`handicap` | for ASIAN handicap markets (I believe!), default is 0
`side` | **BACK** or **LAY**
`limitOrder` | list with details of the bet, required if `orderType` is **LIMIT**, use [`limitOrder`](orders.html#limitorder) to help construct correct list
`limitOnCloseOrder` | list with details of the bet, required if `orderType` is **LIMIT\_ON\_CLOSE**, use [`limitOnCloseOrder`](orders.html#limitoncloseorder) to help construct correct list
`marketOnCloseOrder` | single number, the size of your bet to be placed at Betfairs SP.

### return

A list with details about the bet, the market the bet was made in, the order type, and whether it was successful or failed


<a href="https://github.com/durtal/betfaiR" class="github-corner"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#d9230f; color:#fcfcfc; position: absolute; top: 0; border: 0; right: 0;"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>
